- name: PORT UP LIGHTBULB
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: CHANGE LIGHT TO RED
    uri:
      url: https://maker.ifttt.com/trigger/portup/with/key/ggptzVzHy_FBU0ZtWG0HC-JePGmZM7ZtGJN_ioVUfrY 
      method: POST
