---

- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: all
  connection: local
  gather_facts: False

  tasks:

    - name: GET INTERFACES IN REAL TIME
      ntc_show_command:
        connection: ssh
        platform: "{{ platform }}"
        command: "show interfaces"
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        use_templates: True
        template_dir: ntc-templates/templates/
      register: result
    - debug: var=result['response'][1]['link_status']

- include: redlight.yml
  include: repairint.yml
  when: "'administratively down' in status"
  vars:
    status: "{{ hostvars['csr.interop19.interop.net']['result']['response'][1]['link_status'] }}"

- include: greenlight.yml
  when: "'up' in status"
  vars:
    status: "{{ hostvars['csr.interop19.interop.net']['result']['response'][1]['link_status'] }}"
